/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PD7WJcgyDWp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function InvoiceLanding() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Invoice Automation</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Features
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Pricing
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Streamline Your Invoicing with Invoice Automation
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Automate your invoicing process and save time, reduce errors, and improve cash flow.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Get Started
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Key Features</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Streamline Your Invoicing Process</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Invoice Automation provides a comprehensive solution to automate your invoicing process, saving you
                  time and reducing errors.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="flex flex-col justify-center space-y-4">
                <ul className="grid gap-6">
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Automated Invoice Generation</h3>
                      <p className="text-muted-foreground">
                        Generate invoices automatically based on your sales data, reducing manual work and errors.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Customizable Templates</h3>
                      <p className="text-muted-foreground">
                        Customize your invoice templates to match your brand and include all the necessary information.
                      </p>
                    </div>
                  </li>
                  <li>
                    <div className="grid gap-1">
                      <h3 className="text-xl font-bold">Automated Reminders</h3>
                      <p className="text-muted-foreground">
                        Set up automated payment reminders to ensure timely payments and improve cash flow.
                      </p>
                    </div>
                  </li>
                </ul>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Benefits</div>
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Unlock the Benefits of Invoice Automation
              </h2>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Invoice Automation helps you streamline your invoicing process, improve cash flow, and focus on growing
                your business.
              </p>
            </div>
            <div className="flex flex-col gap-4 min-[400px]:flex-row lg:justify-end">
              <div className="grid gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="h-5 w-5 text-green-500" />
                  <p className="text-muted-foreground">Reduced errors and improved accuracy</p>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="h-5 w-5 text-green-500" />
                  <p className="text-muted-foreground">Faster payment processing and improved cash flow</p>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="h-5 w-5 text-green-500" />
                  <p className="text-muted-foreground">Increased productivity and time savings</p>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="h-5 w-5 text-green-500" />
                  <p className="text-muted-foreground">Improved customer satisfaction</p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Customers Say</h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from our satisfied customers about how Invoice Automation has transformed their invoicing process.
              </p>
            </div>
            <div className="divide-y rounded-lg border">
              <div className="grid w-full grid-cols-1 items-stretch justify-center divide-x md:grid-cols-3">
                <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                  <img
                    src="/placeholder.svg"
                    width="80"
                    height="80"
                    alt="Customer"
                    className="rounded-full"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }}
                  />
                  <div className="text-center">
                    <p className="font-medium">John Doe</p>
                    <p className="text-muted-foreground">CEO, Acme Inc.</p>
                  </div>
                  <p className="text-muted-foreground">
                    "Invoice Automation has been a game-changer for our business. It has streamlined our invoicing
                    process, reduced errors, and improved our cash flow."
                  </p>
                </div>
                <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                  <img
                    src="/placeholder.svg"
                    width="80"
                    height="80"
                    alt="Customer"
                    className="rounded-full"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }}
                  />
                  <div className="text-center">
                    <p className="font-medium">Jane Smith</p>
                    <p className="text-muted-foreground">CFO, Widgets Inc.</p>
                  </div>
                  <p className="text-muted-foreground">
                    "I highly recommend Invoice Automation to any business looking to streamline their invoicing
                    process. It has saved us so much time and hassle."
                  </p>
                </div>
                <div className="mx-auto flex w-full flex-col items-center justify-center p-4 sm:p-8 space-y-4">
                  <img
                    src="/placeholder.svg"
                    width="80"
                    height="80"
                    alt="Customer"
                    className="rounded-full"
                    style={{ aspectRatio: "80/80", objectFit: "cover" }}
                  />
                  <div className="text-center">
                    <p className="font-medium">Michael Johnson</p>
                    <p className="text-muted-foreground">Owner, Gadgets LLC.</p>
                  </div>
                  <p className="text-muted-foreground">
                    "Invoice Automation has been a game-changer for our business. It has streamlined our invoicing
                    process, reduced errors, and improved our cash flow."
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
            <div className="space-y-2">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Pricing</div>
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Affordable Pricing for Every Business
              </h2>
              <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Choose the plan that best fits your business needs and budget.
              </p>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              <Card className="space-y-4">
                <CardHeader>
                  <CardTitle>Starter</CardTitle>
                  <CardDescription>For small businesses</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p className="text-4xl font-bold">$19</p>
                    <p className="text-muted-foreground">per month</p>
                  </div>
                  <ul className="grid gap-2 py-4">
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Automated invoice generation</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Customizable invoice templates</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Automated payment reminders</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Basic reporting and analytics</p>
                    </li>
                  </ul>
                </CardContent>
                <CardFooter>
                  <Button>Get Started</Button>
                </CardFooter>
              </Card>
              <Card className="space-y-4">
                <CardHeader>
                  <CardTitle>Pro</CardTitle>
                  <CardDescription>For growing businesses</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p className="text-4xl font-bold">$49</p>
                    <p className="text-muted-foreground">per month</p>
                  </div>
                  <ul className="grid gap-2 py-4">
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Automated invoice generation</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Customizable invoice templates</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Automated payment reminders</p>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckIcon className="h-5 w-5 text-green-500" />
                      <p>Advanced reporting and analytics</p>
                    </li>
                    <li className />
                  </ul>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
