/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/08iluv7wyVE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function IntegrateWithCrm() {
  return (
    <div className="w-full max-w-5xl mx-auto py-12 md:py-20 lg:py-24">
      <div className="px-4 md:px-6">
        <div className="space-y-4 text-center">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Integrartion</h1>
          <p className="max-w-[700px] mx-auto text-muted-foreground md:text-xl">
            Connect your CRM system to our platform and unlock powerful features to streamline your workflows.
          </p>
        </div>
        <div className="mt-10 md:mt-16 grid grid-cols-1 md:grid-cols-2 gap-10 md:gap-16">
          <div>
            <h2 className="text-2xl font-bold">Integration Process</h2>
            <p className="mt-4 text-muted-foreground">
              Follow these simple steps to integrate your CRM with our platform:
            </p>
            <ol className="mt-6 space-y-4 list-decimal pl-6">
              <li>Provide your CRM credentials in the form below to connect your account.</li>
              <li>
                Select the data you want to sync between the two systems, such as contacts, leads, and opportunities.
              </li>
              <li>Configure any additional settings to customize the integration to your needs.</li>
              <li>Review the integration summary and activate the connection.</li>
            </ol>
          </div>
          <div className="bg-muted rounded-lg p-6 md:p-8">
            <h2 className="text-2xl font-bold">Connect Your CRM</h2>
            <form className="mt-6 space-y-4">
              <div>
                <label htmlFor="crm-type" className="block text-sm font-medium">
                  CRM Type
                </label>
                <select
                  id="crm-type"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                >
                  <option>Zoho</option>
                  <option>Salesforce</option>
                  <option>HubSpot</option>
                  <option>Other</option>
                </select>
              </div>
              <div>
                <label htmlFor="crm-username" className="block text-sm font-medium">
                  CRM Username
                </label>
                <input
                  type="text"
                  id="crm-username"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="Enter your CRM username"
                />
              </div>
              <div>
                <label htmlFor="crm-password" className="block text-sm font-medium">
                  CRM Password
                </label>
                <input
                  type="password"
                  id="crm-password"
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="Enter your CRM password"
                />
              </div>
              <div>
                <label htmlFor="sync-preferences" className="block text-sm font-medium">
                  Sync Preferences
                </label>
                <textarea
                  id="sync-preferences"
                  rows={3}
                  className="mt-1 block w-full rounded-md border-input bg-background px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                  placeholder="Specify which data you want to sync"
                />
              </div>
              <Button type="submit" className="w-full">
                Connect CRM
              </Button>
            </form>
          </div>
        </div>
        <div className="mt-10 md:mt-16">
          <h2 className="text-2xl font-bold">Benefits of Integration</h2>
          <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-6 md:gap-10">
            <div className="bg-muted rounded-lg p-6 md:p-8">
              <div className="flex items-center gap-4">
                <FolderSyncIcon className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold">Seamless Data Sync</h3>
              </div>
              <p className="mt-4 text-muted-foreground">
                Automatically sync your CRM data with our platform, ensuring your team always has the latest
                information.
              </p>
            </div>
            <div className="bg-muted rounded-lg p-6 md:p-8">
              <div className="flex items-center gap-4">
                <BotIcon className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold">Automated Workflows</h3>
              </div>
              <p className="mt-4 text-muted-foreground">
                Streamline your processes by automating tasks and notifications between your CRM and our platform.
              </p>
            </div>
            <div className="bg-muted rounded-lg p-6 md:p-8">
              <div className="flex items-center gap-4">
                <InfoIcon className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold">Powerful Insights</h3>
              </div>
              <p className="mt-4 text-muted-foreground">
                Gain deeper insights by combining data from your CRM and our platform, enabling better decision-making.
              </p>
            </div>
            <div className="bg-muted rounded-lg p-6 md:p-8">
              <div className="flex items-center gap-4">
                <CombineIcon className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold">Improved Collaboration</h3>
              </div>
              <p className="mt-4 text-muted-foreground">
                Foster better collaboration between your sales, marketing, and support teams by connecting your CRM and
                our platform.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function BotIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function CombineIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="8" height="8" x="2" y="2" rx="2" />
      <path d="M14 2c1.1 0 2 .9 2 2v4c0 1.1-.9 2-2 2" />
      <path d="M20 2c1.1 0 2 .9 2 2v4c0 1.1-.9 2-2 2" />
      <path d="M10 18H5c-1.7 0-3-1.3-3-3v-1" />
      <polyline points="7 21 10 18 7 15" />
      <rect width="8" height="8" x="14" y="14" rx="2" />
    </svg>
  )
}


function FolderSyncIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v.5" />
      <path d="M12 10v4h4" />
      <path d="m12 14 1.535-1.605a5 5 0 0 1 8 1.5" />
      <path d="M22 22v-4h-4" />
      <path d="m22 18-1.535 1.605a5 5 0 0 1-8-1.5" />
    </svg>
  )
}


function InfoIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  )
}
